storage: ./storage
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '**':
    access: $anonymous
    publish: $anonymous
log: { type: stdout, format: pretty, level: http }
max_body_size: 500mb
