# Publish Storybooks builds on Chromatic

name: "Chromatic"

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install & build
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Publish monday-ui-react-core to Chromatic
        uses: chromaui/action@v1
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/monday-ui-react-core
          #skip: "gh-pages-*" # skip gh-pages branches - probably will be renamed in the future, so commented out for now
      - name: Publish monday-ui-style to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/monday-ui-style
      - name: Publish vibe-storybook-components to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/vibe-storybook-components
