# Publish Storybooks builds on Chromatic

name: "Chromatic monday-ui-react-core"

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install & build
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Publish to Chromatic
        run: |
          lerna run chromatic --since origin/master
