name: Release

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install and build
        run: |
          yarn --frozen-lockfile
          yarn build
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
