name: Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install and build
        run: |
          yarn install --frozen-lockfile
          yarn build
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - name: Test
        if: success()
        run: |
          yarn test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install and build
        run: |
          yarn install --frozen-lockfile
          yarn build
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - name: Test
        if: success()
        run: |
          yarn lint

  build-storybook-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install and build
        run: |
          yarn install --frozen-lockfile
          yarn build
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - name: Test
        if: success()
        run: |
          yarn build-storybook
